### ISSUE TITLE
Calling selectAll(false) open the dialog box

### ISSUE THREAD

**Issue by xavArtley** [minisuperfiles/MSFmultiSelect#22]
![image](https://user-images.githubusercontent.com/18531147/124635656-f78b8800-de87-11eb-9dc2-d894fbf28b3a.png)

expected result:
![image](https://user-images.githubusercontent.com/18531147/124635721-05410d80-de88-11eb-8424-7d04c1ecfc90.png)

**Comment by jagadeesanjd11** [comment]
Now fixed this bug in version 2.2.
If face any problem raise a new issue.
Thanks 👍🏾
