### ISSUE TITLE
Removing an item using the close button of an element does not trigger onChange callback

### ISSUE THREAD

**Issue by xavArtley** [minisuperfiles/MSFmultiSelect#23]
![onchange_not_triggered](https://user-images.githubusercontent.com/18531147/124640488-c31aca80-de8d-11eb-94e4-70758fd3542a.gif)

**Comment by jagadeesanjd11** [comment]
Now fixed this bug in version 2.2.
If face any problem raise a new issue.
Thanks 👍🏾
