### ISSUE TITLE
SearchBox content inconsistent when reopen

### ISSUE THREAD

**Issue by xavArtley** [minisuperfiles/MSFmultiSelect#24]
Closing the search box and reopening it clear the content inside it however the options are stay filtered
![search_bug](https://user-images.githubusercontent.com/18531147/124785955-988d4800-df47-11eb-9b56-ba445e8ba3a2.gif)

**Comment by balaJS** [comment]
@jagadeesanjd11 Please build the min files.
@xavArtley  Thanks for raise a issue. Once the build is completed, we will notify you

**Comment by jagadeesanjd11** [comment]
@xavArtley 
Now fixed this bug in version 2.3.
If face any problem raise a new issue.
Thanks 👍🏾

**Comment by xavArtley** [comment]
Cool you have corrected in the meantime the AllSelect checked box
