### ISSUE TITLE
Discussion on selectAll checkbox behavior

### ISSUE THREAD

**Issue by xavArtley** [minisuperfiles/MSFmultiSelect#25]
When an option is unselect, the selectAll checked box stay active
Was wondering if the checked state of the selectAll check box should not reflect the fact that all options are selected
Moreover if we use the searchBox and all options are not selected, the selectedAll checkbox is unchecked
![selectAll](https://user-images.githubusercontent.com/18531147/125043028-cfc03e00-e09a-11eb-94fc-97fc3ee5cb3d.gif)

**Comment by jagadeesanjd11** [comment]
@xavArtley
Now fixed this bug in version 2.4.
If face any problem raise a new issue.
Thanks 👍🏾
