### ISSUE TITLE
Search reset when selecting an item 

### ISSUE THREAD

**Issue by xavArtley** [minisuperfiles/MSFmultiSelect#26]
I can't reopen issue #24 
![search_reset](https://user-images.githubusercontent.com/18531147/125047760-92aa7a80-e09f-11eb-9906-7e38337017a0.gif)

**Comment by jagadeesanjd11** [comment]
onChange inside don't use reload method. If it is not work, send your code.

**Comment by xavArtley** [comment]
indeed changing my code make it works
